class FlightClosed(Exception): ...


class FlightDeparted(Exception): ...


class FlightNotFound(Exception): ...


class FlightAlreadyExists(Exception): ...


class SeatAlreadyReserved(Exception): ...


class SeatDoesNotExist(Exception): ...


class PassengerAlreadyRegistered(Exception): ...


class NotReservationOwner(Exception): ...
